[project]
name = "lab-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pymupdf>=1.26.4",
    "python-docx>=1.2.0",
    "sentence-transformers>=5.1.1",
    "watchdog>=6.0.0",
]
